name: Create docker image for GitHub Action

on:
  release:
    types: 
      - published

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF##*v})

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_kfp
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: albertcintaspot/kfp-delete:${{ steps.get_version.outputs.VERSION }},albertcintaspot/kfp-delete:latest
